### ISSUE TITLE
Inconsistent variable naming leading to error

### ISSUE THREAD

**Issue by cmd-c-cmd-v** [prolix-oc/Refyne#14]
BCD backup filepath is defined in the ['Logging and Backup Paths'](https://github.com/prolix-oc/Refyne/blob/36d9c4ff981bd7113e91b0abb655eee331460a77/Refyne.ps1#L46-L50) section

https://github.com/prolix-oc/Refyne/blob/36d9c4ff981bd7113e91b0abb655eee331460a77/Refyne.ps1#L50

Later referenced in the [Undo-SystemChanges](https://github.com/prolix-oc/Refyne/blob/36d9c4ff981bd7113e91b0abb655eee331460a77/Refyne.ps1#L527C1-L562) function incorrectly

https://github.com/prolix-oc/Refyne/blob/36d9c4ff981bd7113e91b0abb655eee331460a77/Refyne.ps1#L554

**Comment by prolix-oc** [comment]
Issue previously fixed by 72d9c06e56a103222da94dea1734ddc25e8cb98b which has already been promoted into release, thanks so much for the contribution!

**Comment by cmd-c-cmd-v** [comment]
> Issue previously fixed by [72d9c06](https://github.com/prolix-oc/Refyne/commit/72d9c06e56a103222da94dea1734ddc25e8cb98b) which has already been promoted into release, thanks so much for the contribution!

The lines referenced in https://github.com/prolix-oc/Refyne/issues/14#issue-2086859564 are still present in the latest version of [Refyne.ps1](https://github.com/prolix-oc/Refyne/blob/3422d176925380004a29661f30fb234fc36c9aed/Refyne.ps1)

**Comment by prolix-oc** [comment]
Indeed it is, huh. No clue how that escaped my search. Thanks for letting me know!

**Comment by prolix-oc** [comment]
Fixed (for real) in commit 5efca6d

Thanks again!
